# Generated by Django 3.2.4 on 2021-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokes',
            name='joke_rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
