# Generated by Django 3.2.4 on 2021-12-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokes',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jokes',
            name='joke_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='jokes',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jokes',
            name='joke_text',
            field=models.TextField(max_length=500, verbose_name='Текст шутки'),
        ),
    ]
