# Generated by Django 3.2.4 on 2021-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211127_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='joke_text',
            field=models.CharField(max_length=500, verbose_name='Текст шутки'),
        ),
    ]
