# Generated by Django 3.2.4 on 2021-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211202_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='joke_rating',
            field=models.IntegerField(default=3),
        ),
    ]
