# Generated by Django 3.2.4 on 2021-12-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_jokes_joke_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokes',
            name='owner',
            field=models.ForeignKey(default='user2', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jokes',
            name='joke_rating',
            field=models.IntegerField(default=7),
        ),
    ]
